In [10]:
#Assignment 1
import numpy as np

def GeometricProgressionMatrix(x,increasing):
    if(increasing=='False'):
        length=len(x)  #Calculating length of x
        n=np.column_stack([x**(length - i - 1) for i in range(length)])  #Calculating Geometric progression
    return n

x=np.array([1,2,3,4])
returnarray = GeometricProgressionMatrix(x,'False')
print(returnarray)


[[ 1  1  1  1]
 [ 8  4  2  1]
 [27  9  3  1]
 [64 16  4  1]]
